### ISSUE TITLE
copyright

### ISSUE THREAD

**Issue by Laphatize** [versocre/bastpc#5]
this software has the word "Ellie" which is a copyrighted symbol

remove or sue for $50

hup hup honeu buns

**Comment by versocre** [comment]
Hi there, BaSTPC connects to the STiBaRC services, so any posts from STiBaRC will show on BaSTPC. The same goes for any posts made on BaSTPC, they will show on STiBaRC.

**Comment by Laphatize** [comment]
this was a joke everyone
